# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

workspace 'YMWrapper'

def yousimed_pods
  #Pods for yousimed
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end

def onboarding_pods
  #Pods for onboarding module
end


target 'YousiMed' do
  project 'YousiMed.xcodeproj'
  
  yousimed_pods
  onboarding_pods
  
  target 'YousiMedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YousiMedUITests' do
    # Pods for testing
  end

end

target 'FROnboarding' do
  project '../ios-fr-onboarding-main/FROnboarding.xcodeproj'
  onboarding_pods
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
     end
   end
end
